apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: add-task
spec:
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
  results:
    - name: sum
      description: the sum of the first and second operand
  steps:
    - name: add
      image: alpine
      env:
        - name: OP1
          value: $(params.first)
        - name: OP2
          value: $(params.second)
      command: ["/bin/sh", "-c"]
      args:
        - echo -n "my-pvc-4" | tee $(results.sum.path);
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sum-three-pipeline
spec:
  workspaces:
    - name: ss
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
    - name: third
      description: the third operand
  tasks:
    - name: first-add
      taskRef:
        name: add-task
      params:
        - name: first
          value: $(params.first)
        - name: second
          value: $(params.second)
    - name: use-workspace-from-results
      workspaces:
        - name: aa
          workspace: ss
      runAfter:
        - first-add
      taskSpec:
        steps:
          - name: write-allowed
            image: ubuntu
            script: echo "hello" > $(workspaces.aa.path)/foo
          - name: read-allowed
            image: ubuntu
            script: cat $(workspaces.aa.path)/foo | grep "hello"
  results:
    - name: partial-sum
      description: the sum of first two operands
      value: $(tasks.first-add.results.sum)
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sum-three-pipeline-run
spec:
  pipelineRef:
    name: sum-three-pipeline
  params:
    - name: first
      value: "2"
    - name: second
      value: "10"
    - name: third
      value: "10"
    - name: four
      value: "my-pvc-3"
  workspaces:
    - name: "ss"
      persistentVolumeClaim:
        claimName: $(tasks.first-add.results.sum)
