apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: step-action-consuming-artifacts
spec:
  params:
    - name: image-artifact-provenance
  image: endeveit/docker-jq
  command:
    - sh
    - -c
    - "echo '$(params.image-artifact-provenance)' | jq '.[0].digest.sha256'"
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: step-artifacts-
spec:
  taskSpec:
    description: |
      A simple task that populates artifacts to TaskRun stepState
    steps:
      - name: artifacts-producer
        image: bash:latest
        script: |
          cat > $(step.artifacts.path) << EOF
          {
            "inputs":[
              {
                "name":"input-artifacts",
                "values":[
                  {
                    "uri":"git:jjjsss",
                    "digest":{
                      "sha256":"b35cacccfdb1e24dc497d15d553891345fd155713ffe647c281c583269eaaae0"
                    }
                  }
                ]
              }
            ],
            "outputs":[
              {
                "name":"build-result",
                "values":[
                  {
                    "uri":"pkg:balba",
                    "digest":{
                      "sha256":"df85b9e3983fe2ce20ef76ad675ecf435cc99fc9350adc54fa230bae8c32ce48",
                      "sha1":"95588b8f34c31eb7d62c92aaa4e6506639b06ef2"
                    }
                  }
                ]
              }
            ]
          }
          EOF
      - name: artifacts-consumer
        image: bash:latest
        script: |
          echo $(steps.artifacts-producer.outputs)
      - name: consuming-artifacts-ref
        ref:
          name: step-action-consuming-artifacts
        params:
          - name: image-artifact-provenance
            value: $(steps.artifacts-producer.outputs.build-result)
