apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-3
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: workspaces-readonly-
spec:
  params:
    - name: aaaa
      value: my-pvc-3

  workspaces:
    - name: write-allowed
      persistentVolumeClaim:
        claimName: $(params.aaaa)
    - name: write-disallowed
      persistentVolumeClaim:
        claimName: $(params.aaaa)
  taskSpec:
    workspaces:
    - name: write-allowed
    - name: write-disallowed
      readOnly: true
    steps:
    - name: write-allowed
      image: ubuntu
      script: echo "hello" > $(workspaces.write-allowed.path)/foo
    - name: read-allowed
      image: ubuntu
      script: cat $(workspaces.write-allowed.path)/foo | grep "hello"
    - name: write-disallowed
      image: ubuntu
      script:
        echo "goodbye" > $(workspaces.write-disallowed.path)/foo || touch write-failed.txt
        test -f write-failed.txt
    - name: read-again
      # We should get "hello" when reading again because writing "goodbye" to
      # the file should have been disallowed.
      image: ubuntu
      script:
        cat $(workspaces.write-disallowed.path)/foo | grep "hello"
